[package]
name = "sabrelite-bsp"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2021"
build = "build.rs"

[dependencies]
ferros = { git = "https://github.com/auxoncorp/ferros.git" }
bitflags = "1.3"
log = "0.4"

[dependencies.imx6-hal]
path = "../imx6-hal"
